### ISSUE TITLE
Links To Changesets Not Updated

### ISSUE THREAD

**Issue by mwaeckerlin** [seantis/git-svn-trac#2]
Links to changesets are not properly updated. And if that is fixed, the link is not set, since the text "changeset:" is missing.

Bugfix 1: Regular expression on line 64 is missing a quote. Even better: specify the quotes as optional.
Bugfix 2: Add the text "changeset:" on line 74

Please apply the attached patch: [patch.txt](https://github.com/seantis/git-svn-trac/files/106607/patch.txt)

**Comment by href** [comment]
Thanks for the patch. I'm not using this migration tool anymore, having migrated everything already. However I'm happy to accept bug fixes.

That being said, I'm not sure why you should add 'changeset:' in line 74. From what I know `[1234]` is a valid reference to a changeset. Is this required in newer versions of trac?

**Comment by mwaeckerlin** [comment]
At least in my version of trac it seems to be required — Well, with subversion, the changeset is in numbers-only, but not in git, perhaps that's the background? So in my trac, link without `changeset:` did not work.

We're just now migrating some projects from svn to git. I'll provide you with more infos, should I trap into something.

Sidenote1: I'd be glad if you could work-in the patch, even though you're not using it any more. Otherwise I'd have to clone the project and other users could be confused on what the latest and most accurate version is.
Sidenote2: Wow, icon from Moss of «The IT Crowd», so I'm not the only nerd around here … ;)

**Comment by href** [comment]
Well then that's good enough for me. [I applied your patch](https://github.com/seantis/git-svn-trac/commit/a75195fc55227b3502c0774d207a642f0147bbb1). Should anyone want it the old way they can either use an older version or I can add a config switch.

Thank you!

**Comment by mwaeckerlin** [comment]
thx
